default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: todo
  password: todopassword

development:
  <<: *default
  database: todo_development

test:
  <<: *default
  database: todo_test

production:
  <<: *default
  database: todo_app_production
  username: todo
  password: <%= ENV['TODO_DATABASE_PASSWORD'] %>